server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
    session:
      timeout: 480m
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kea-002-blog.cluster-cne10fapbpfh.us-east-1.rds.amazonaws.com:3306/service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: admin
    password: ${DB_PASSWORD}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show-sql: true

logging:
  level:
    org:
      springframework:
        web=DEBUG: